apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: ravisrma/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: REACT_APP_API_BASE_URL
            value: "http://example.com//backend"
          - name: NODE_OPTIONS
            value: "--openssl-legacy-provider"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"