services:
  database:
    image: database-image:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend-image:latest
    container_name: backend-container
    environment:
      host: mysql-container
      user: root
      password: mysql123
      database: school
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    image: frontend-image:latest
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: