# filepath: /home/ravi/MERN-Stack-Project/student-teacher-app/Dockerfile-Frontend
# Stage 1: Build the application using Node.js
FROM node:21-alpine3.17 AS build
WORKDIR /app
COPY . .
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000
RUN npm install
RUN npm update
RUN npm run build

# Stage 2: Run the application
FROM node:21-alpine3.17
WORKDIR /app
COPY --from=build /app /app
ENV NODE_OPTIONS=--openssl-legacy-provider
CMD ["npm", "start"]