apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: ravisrma/database:latest
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: database
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mypvc
              mountPath: /var/lib/mysql
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc
            resources:
              requests:
                storage: 1Gi