apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: three-tier
  namespace: mern
spec:
  ingressClassName: nginx
  rules:
    - host: ravicloudexper.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80