apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: ravisrma/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3500
          livenessProbe:
            httpGet:
              path: backend/
              port: 3500
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: backend/
              port: 3500
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          env:
          - name: host
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: host
          - name: user
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: user
          - name: password
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
          - name: database
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: database
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"