name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy resources."
        required: false
        default: "false"

permissions:
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    if: ${{ github.event.inputs.destroy != 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      # Set up NodeJS 
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Install NodeJS dependencies
    - name: Install NodeJS dependencies
      run: npm install
      working-directory: ./student-teacher-app

    # SonarQube Analysis
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    # Build Frontend Docker image
    - name: Build Frontend Docker image
      run: |
        docker build -t frontend:${{ github.sha }} -f ./student-teacher-app/Dockerfile-Frontend ./student-teacher-app
        docker tag frontend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
    
    # Build Backend Docker image
    - name: Build Backend Docker image
      run: |
        docker build -t backend:${{ github.sha }} -f ./backend/Dockerfile-Backend ./backend
        docker tag backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
    
    # Build Database Docker image
    - name: Build Database Docker image
      run: |
        docker build -t database:${{ github.sha }} -f ./database/Dockerfile-Database ./database
        docker tag database:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
    
    # Trivy Scan
    - name: Trivy Scan Frontend
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image frontend:${{ github.sha}}
    
    - name: Trivy Scan Backend
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image backend:${{ github.sha}}

    - name: Trivy Scan Database
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image database:${{ github.sha}}

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push image to DockerHub
    - name: Push Frontend image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
    
    - name: Push Backend image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    - name: Push Database image to DockerHub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/database:latest

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        if: github.event_name == 'pull_request'
        continue-on-error: true

      - uses: actions/github-script@v7.0.1
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
            </details>
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            });

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
      
  # deploy_elk:
  #   runs-on: ubuntu-latest
  #   needs: terraform
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   defaults:
  #     run:
  #       shell: bash
  #       working-directory: ./elk

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4.2.2

  #     - name: Configure AWS credentials from AWS account
  #       uses: aws-actions/configure-aws-credentials@v4.0.3
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Install kubectl
  #       run: |
  #         sudo apt-get install kubectl -y

  #     - name: Update kubeconfig
  #       run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name eks-cluster

  #     - name: Wait for resources to be created
  #       run: sleep 30

  #     - name: Deploy ELK Stack
  #       run: | 
  #         kubectl config view
  #         kubectl apply -f . --validate=false
    
  #     - name: Verify kubectl configuration
  #       run: | 
  #         sleep 30
  #         kubectl get svc -n elk

  deploy_elk_helm:
    runs-on: ubuntu-latest
    needs: [terraform]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          sudo apt-get install kubectl -y

      - name: Update kubeconfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name eks-cluster

      - name: Wait for resources to be created
        run: sleep 30

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Elastic Helm Repo
        run: helm repo add elastic https://helm.elastic.co

      - name: Update Helm Repos
        run: helm repo update

      - name: Create and Apply Persistent Volumes for Elasticsearch
        working-directory: ./elasticsearch
        run: kubectl apply -f pv.yaml

      - name: Install Elasticsearch using Helm
        working-directory: ./elasticsearch
        run: helm install elasticsearch elastic/elasticsearch --version="8.5.1" -f values.yaml

      - name: Create and Apply Persistent Volumes for Filebeat
        working-directory: ./filebeat
        run: kubectl apply -f pv.yaml

      - name: Install Filebeat using Helm
        working-directory: ./filebeat
        run: helm install filebeat elastic/filebeat --version="8.5.1" -f values.yaml

      - name: Install Kibana using Helm
        working-directory: ./kibana
        run: helm install kibana elastic/kibana --version="8.5.1"

      - name: Apply Ingress for Kibana
        working-directory: ./kibana
        run: kubectl apply -f ingress.yaml

      - name: Apply Logstash Configuration
        working-directory: ./logstash
        run: kubectl apply -f .

  destroy:
    runs-on: ubuntu-latest
    needs: [terraform]
    if: ${{ github.event.inputs.destroy == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

  notify:
    name: Notify on Slack
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() # Pick up events even if the job fails or is canceled.