name: CI/CD Pipeline for Student Teacher App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set to true to destroy resources."
        required: false
        default: "false"

permissions:
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  ###########################################################################
  # Job 1: Build & Push Docker Image to DockerHub
  ###########################################################################
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up NodeJS 
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install NodeJS dependencies
      - name: Install NodeJS dependencies
        run: npm install
        working-directory: ./student-teacher-app

      # SonarQube Analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      # Build Frontend Docker image
      - name: Build Frontend Docker image
        run: |
          docker build -t frontend:${{ github.sha }} -f ./student-teacher-app/Dockerfile-Frontend ./student-teacher-app
          docker tag frontend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      
      # Build Backend Docker image
      - name: Build Backend Docker image
        run: |
          docker build -t backend:${{ github.sha }} -f ./backend/Dockerfile-Backend ./backend
          docker tag backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
      
      # Build Database Docker image
      - name: Build Database Docker image
        run: |
          docker build -t database:${{ github.sha }} -f ./database/Dockerfile-Database ./database
          docker tag database:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
      
      # Trivy Scan
      - name: Trivy Scan Frontend
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image frontend:${{ github.sha}}
      
      - name: Trivy Scan Backend
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image backend:${{ github.sha}}

      - name: Trivy Scan Database
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image database:${{ github.sha}}

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push image to DockerHub
      - name: Push Frontend image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      
      - name: Push Backend image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Push Database image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/database:latest

  ###########################################################################
  # Job 2: Provision Infrastructure Resources
  ###########################################################################        
  terraform-resources:
    name: Provision Resources
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Git checkout
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@v7.0.1
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
            </details>
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            });

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
  
  ###########################################################################
  # Job 3: Deploy the autoscaler on EKS
  ###########################################################################
  deploy_autoscaler:
    runs-on: ubuntu-latest
    needs: [terraform-resources]
    defaults:
      run:
        shell: bash
        working-directory: ./autoscaler
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          sudo apt-get install kubectl -y

      - name: Update kubeconfig
        run: aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name eks-cluster

      - name: Wait for resources to be created
        run: sleep 30

      - name: Deploy to EKS Autoscaler
        run: |
          kubectl apply -f cluster-autoscaler.yaml

 ###########################################################################
  # Job 4: Send Notification Email (NEW)
  ###########################################################################
  notify:
    name: Send Notification Email
    runs-on: ubuntu-latest
    needs: [docker, terraform-resources, deploy_autoscaler]
    if: always()  # Ensure this job runs regardless of previous outcomes
    steps:
      # Step to determine overall pipeline status
      - name: Determine overall pipeline status
        id: pipeline-status
        run: |
          # Check if all required jobs succeeded
          if [[ "${{ needs.docker.result }}" == "success" ]] \
          && [[ "${{ needs.terraform-resources.result }}" == "success" ]] \
          && [[ "${{ needs.deploy_autoscaler.result }}" == "success" ]]; then
            echo "result=Success ✅" >> $GITHUB_OUTPUT
          else
            echo "result=Failed ❌" >> $GITHUB_OUTPUT
          fi

      # Step to send notification email
      - name: Send Email
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp.gmail.com
          smtp-port: 465
          smtp-secure: true
          from-email: ${{ secrets.MAIL_FROM }}
          to-email: ${{ secrets.MAIL_TO }} # Use a secret for the recipient email addresses
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI/CD Pipeline Notification: ${{ github.workflow }} - ${{ steps.pipeline-status.outputs.result }}"
          body: ""
          html: |
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background-color: #ffffff;">
              <h2 style="color: #24292e; text-align: center;">🚀 CI/CD Pipeline Notification</h2>
      
              <div style="background-color: #f6f8fa; padding: 16px; border-radius: 6px;">
                <table style="width: 100%; border-collapse: collapse;">
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Workflow</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.workflow }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Triggered by</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.actor }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Repository</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">${{ github.repository }}</td>
                  </tr>
                  <tr>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;"><strong>Run Details</strong></td>
                    <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                      <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" style="color: #0366d6; text-decoration: none;">View Run #${{ github.run_id }}</a>
                    </td>
                  </tr>
                </table>
              </div>
      
              <h3 style="margin-top: 16px;">🛠 Job Statuses</h3>
              <table style="width: 100%; border-collapse: collapse; background-color: #fff;">
                <tr style="background-color: #f6f8fa;">
                  <th style="padding: 10px; text-align: left;">Job</th>
                  <th style="padding: 10px; text-align: center;">Status</th>
                </tr>
                <tr>
                  <td style="padding: 10px;">Docker Build</td>
                  <td style="padding: 10px; text-align: center; color: white; background-color: 
                    ${{ (needs.docker.result == 'success' && '#28a745') || '#d73a49' }}; border-radius: 4px;">
                    ${{ needs.docker.result }}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 10px;">Terraform Resources</td>
                  <td style="padding: 10px; text-align: center; color: white; background-color: 
                    ${{ (needs.terraform-resources.result == 'success' && '#28a745') || '#d73a49' }}; border-radius: 4px;">
                    ${{ needs.terraform-resources.result }}
                  </td>
                </tr>
                <tr>
                  <td style="padding: 10px;">Deploy Autoscaler</td>
                  <td style="padding: 10px; text-align: center; color: white; background-color: 
                    ${{ (needs.deploy_autoscaler.result == 'success' && '#28a745') || '#d73a49' }}; border-radius: 4px;">
                    ${{ needs.deploy_autoscaler.result }}
                  </td>
                </tr>
              </table>
      
              <p style="color: #6a737d; font-size: 0.9em; margin-top: 20px; text-align: center;">
                This email was sent automatically by <strong>GitHub Actions</strong>.
              </p>
            </div>